# Generated by Django 4.1.2 on 2022-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project')),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(max_length=32)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
