# Generated by Django 4.1.2 on 2022-10-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
